const catchError = require("../utils/catch-error");
const createError = require("../utils/create-error");

// // admin >> route admin
// module.exports.confirmProductByadmin = async(req, res, next) = {
//     try {

//     } catch(err) {
//         next(err)
//     }
// }

// // seller
// module.exports.sellSuccessfully = async(req, res, next) = {
//     try {

//     } catch(err) {
//         next(err)
//     }
// }

// // buyer
// module.exports.buySuccessfully = async(req, res, next) = {
//     try {

//     } catch(err) {
//         next(err)
//     }
// }
// module.exports.confirmProductByBuyer = async(req, res, next) = {
//     try {

//     } catch(err) {
//         next(err)
//     }
// }
// module.exports.cancelProductByBuyer = async(req, res, next) = {
//     try {

//     } catch(err) {
//         next(err)
//     }
// }
